language: node_js

node_js:
  - "10"
install:
  - yarn install

stages:
  - test
  - name: deploy

jobs:
  include:
  - stage: test
     script:
       - node --version
       - npm --version
       - echo "Testing Started ..."
       - npm test
       - echo "Testing Finished."

   - stage: deploy
     script:
       - echo "NPM Deploying Started ..."
       - npm version
      #  - npm run build
       - echo "NPM Building Finished."

     deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
       skip_cleanup: true
       on:
         all_branches: true
