language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: deploy
jobs:
  include:
    - stage: deploy
      script:
        - echo "NPM Deploying Started ..."
        - npm version
        - echo "NPM Building Finished."
      deploy:
        edge: true
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
